// <auto-generated />
using DeveloperManagement.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeveloperManagement.Migrations
{
    [DbContext(typeof(DevelopersContext))]
    [Migration("20230211040218_mg1")]
    partial class mg1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeveloperManagement.Context.Developers", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeveloperId");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            DeveloperId = 1,
                            Age = 27,
                            JobTitle = "Jr. Developer 1",
                            Name = "Ali"
                        },
                        new
                        {
                            DeveloperId = 2,
                            Age = 29,
                            JobTitle = "Jr. Developer 2",
                            Name = "Osman"
                        },
                        new
                        {
                            DeveloperId = 3,
                            Age = 37,
                            JobTitle = "Sr. Developer 1",
                            Name = "Subhan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
